In [13]:
import pandas as pd
data = pd.read_csv('form.csv', parse_dates=[0])

In [2]:
data.head()

,Отметка времени,Мальчик или девочка?,Как часто тебя били в детстве?,Оцените ваш уровень вегетарианца по 5-ти бальной шкале,Что такое два.ч?,Твоя ориентация?,"Погулять вечером после тяжкого рабочего дня, или посычевать дома?",Как часто играешь в игры?,Сериалы?,А книги?,Вы таки антисемит?,Какой предмет ближе всего по душе?,Как вы относитесь к аннексии Крыма?,Владимир Путин -,Как хорошо вы знаете английский?,Было ли раньше лучше?,А какие жанры фильмов любишь?
0,2019-09-06 23:22:11,Девочка,Не били,2,Не знаю,Гетеро,Сычевать,1,1,3,Нет,Литература,Положительно,Краб,"Чуть лучше, чем ничего",Нет,"Детектив, Аниме, Драма, Комедия, Исторический ..."
1,2019-09-06 23:27:43,Мальчик,Разве что по делу,2,Ненавижу Абу,Гетеро,Сычевать,3,1,2,Нет,Матеша,Мне всё равно,человек,Хорошо,Нет,"Детектив, Трагедия, Фильм ужасов, Фантастика"
2,2019-09-06 23:30:07,Девочка,Разве что по делу,2,Паблик в вк,Гетеро,Гулять,0,1,3,Нет,Информатика,Мне всё равно,"Политик, лидер и боец",Хорошо,Нет,"Боевик, Детектив, Комедия, Мелодрама, Фантастика"
3,2019-09-06 23:30:08,Мальчик,Разве что по делу,0,Лучшая борда рунета,Гетеро,Гулять,2,3,4,Нет,Информатика,Отрицательно,"Политик, лидер и боец",Хорошо,"А колбаса какая, колбаса...","Боевик, Детектив, Аниме, Комедия, Мелодрама, И..."
4,2019-09-06 23:31:38,Мальчик,Не били,1,Ненавижу Абу,Гетеро,Сычевать,6,4,3,Нет,Информатика,Мне всё равно,"Политик, лидер и боец","Чуть лучше, чем ничего","А колбаса какая, колбаса...","Боевик, Детектив, Аниме, Драма, Комедия, Истор..."

In [14]:
data.columns = ['time', 'sex', 'child_offence', 'vegan', 'dvach', 'gender', 'rest', 'games', 'series', 'books', 'antisemetism', 'subject', 'crimea', 'putin', 'english', 'old_days', 'films']

data.loc[data['sex'] != 'Девочка', ['sex']] = 0
data.loc[data['sex'] == 'Девочка', ['sex']] = 1

data.loc[data['rest'] != 'Сычевать', ['rest']] = 0
data.loc[data['rest'] == 'Сычевать', ['rest']] = 1

data.loc[data['english'] == 'Оригатоё гайзаймас', ['english']] = 0
data.loc[data['english'] == 'Чуть лучше, чем ничего', ['english']] = 1
data.loc[data['english'] == 'Нормально', ['english']] = 2
data.loc[data['english'] == 'Хорошо', ['english']] = 3
data.loc[data['english'] == 'Отлично', ['english']] = 4
data.loc[data['english'] == 'НЭЙТИВ ИНГЛИШ СПИКЕР', ['english']] = 5

In [16]:
child_offence = pd.get_dummies(data.child_offence)
dvach = pd.get_dummies(data.dvach)
gender = pd.get_dummies(data.gender)
antisemetism = pd.get_dummies(data.antisemetism)
subject = pd.get_dummies(data.subject)
crimea = pd.get_dummies(data.crimea)


child_offence.columns = ['not_beaten', 'beat_otc', 'beaten']
dvach.columns = ['best_runet_board', 'dvach_dont_know', 'hate_abu', 'vk_puplic']
gender.columns = ['alternative_gender', 'bi_gender', 'getero_gender']
antisemetism.columns = ['antisemit', 'not_antisemit', 'afraid_of_jews']
subject.columns = ['biology', 'foreign_language', 'it', 'history', 'literature', 'math', 'physics', 'chemistry']
crimea.columns = ['dont_care_annexation', 'for_annexation', 'against_annexation']


data = data.drop('child_offence', axis=1).join(child_offence)
data = data.drop('dvach', axis=1).join(dvach)
data = data.drop('gender', axis=1).join(gender)
data = data.drop('antisemetism', axis=1).join(antisemetism)
data = data.drop('subject', axis=1).join(subject)
data = data.drop('crimea', axis=1).join(crimea)

In [17]:
data.head()

,time,sex,vegan,rest,games,series,books,putin,english,old_days,...,foreign_language,it,history,literature,math,physics,chemistry,dont_care_annexation,for_annexation,against_annexation
0,2019-09-06 23:22:11,1,2,1,1,1,3,Краб,1,Нет,...,0,0,0,1,0,0,0,0,0,1
1,2019-09-06 23:27:43,0,2,1,3,1,2,человек,3,Нет,...,0,0,0,0,1,0,0,1,0,0
2,2019-09-06 23:30:07,1,2,0,0,1,3,"Политик, лидер и боец",3,Нет,...,0,1,0,0,0,0,0,1,0,0
3,2019-09-06 23:30:08,0,0,0,2,3,4,"Политик, лидер и боец",3,"А колбаса какая, колбаса...",...,0,1,0,0,0,0,0,0,1,0
4,2019-09-06 23:31:38,0,1,1,6,4,3,"Политик, лидер и боец",1,"А колбаса какая, колбаса...",...,0,1,0,0,0,0,0,1,0,0

In [18]:
def putin_parse(row):
    if row.putin == 'Политик, лидер и боец':
        return pd.Series([1, 0])
    return pd.Series([0, 1])

data[['putin_good', 'rebel']] = data.apply(putin_parse, axis=1)
data.drop('putin', axis = 1, inplace=True)

In [367]:
data.head()

,time,sex,vegan,rest,games,series,books,old_days,films,cf1,...,cr2,cr3,eng1,eng2,eng3,eng4,eng5,eng6,putin_good,rebel
0,2019-09-06 23:22:11,1,2,1,1,1,3,Нет,"Детектив, Аниме, Драма, Комедия, Исторический ...",1,...,0,1,0,0,0,0,0,1,0,1
1,2019-09-06 23:27:43,0,2,1,3,1,2,Нет,"Детектив, Трагедия, Фильм ужасов, Фантастика",0,...,0,0,0,0,0,0,1,0,0,1
2,2019-09-06 23:30:07,1,2,0,0,1,3,Нет,"Боевик, Детектив, Комедия, Мелодрама, Фантастика",0,...,0,0,0,0,0,0,1,0,1,0
3,2019-09-06 23:30:08,0,0,0,2,3,4,"А колбаса какая, колбаса...","Боевик, Детектив, Аниме, Комедия, Мелодрама, И...",0,...,1,0,0,0,0,0,1,0,1,0
4,2019-09-06 23:31:38,0,1,1,6,4,3,"А колбаса какая, колбаса...","Боевик, Детектив, Аниме, Драма, Комедия, Истор...",1,...,0,0,0,0,0,0,0,1,1,0

In [19]:
# Составляем список всех доступных жанров
ganres = set()
for i, row in data.iterrows():
    for ganre in row.films.split(','):
        ganres.add(ganre.strip())
        

# Создаём колонки под фильмы        
for g in ganres:
    data[g] = 0


# Запоняем колонки
for i, row in data.iterrows():
    for ganre in row.films.split(','):
        data.loc[i, ganre.strip()] = 1

# Переименовываем колонки
data.drop('films', axis=1, inplace=True)
old_names = sorted(list(ganres))
new_names = sorted(['anine', 'triller', 'detective', 'drama', 'historical', 'comedy', 'melodrama', 'tragedy', 'fantasy', 'horror'])

for i, g in enumerate(old_names):
    data.rename(columns={g: new_names[i]}, inplace=True)

In [20]:
data.head()

,time,sex,vegan,rest,games,series,books,english,old_days,not_beaten,...,historical,detective,fantasy,melodrama,triller,comedy,anine,tragedy,horror,drama
0,2019-09-06 23:22:11,1,2,1,1,1,3,1,Нет,1,...,1,1,1,1,0,0,1,1,0,1
1,2019-09-06 23:27:43,0,2,1,3,1,2,3,Нет,0,...,0,1,0,1,1,0,0,1,0,0
2,2019-09-06 23:30:07,1,2,0,0,1,3,3,Нет,0,...,1,1,0,0,0,1,0,1,1,0
3,2019-09-06 23:30:08,0,0,0,2,3,4,3,"А колбаса какая, колбаса...",0,...,1,1,1,0,0,1,1,1,1,0
4,2019-09-06 23:31:38,0,1,1,6,4,3,1,"А колбаса какая, колбаса...",1,...,1,1,1,0,1,1,1,0,0,1

In [21]:
data.to_csv('new_table.csv')